# Generated by Django 6.0 on 2026-02-03 07:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0003_user_avatar'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='avatar',
            field=models.ImageField(default='media/account/03.jpg', upload_to='account', verbose_name='آواتار'),
        ),
    ]
