# Generated by Django 6.0 on 2026-01-04 16:38

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='movie',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(blank=True, max_length=300, null=True, verbose_name='عنوان فیلم')),
                ('day', models.CharField(blank=True, max_length=300, null=True, verbose_name='روز اکران')),
                ('movie_time', models.CharField(blank=True, max_length=300, null=True, verbose_name='مدت زمان')),
                ('capacity', models.CharField(blank=True, max_length=300, null=True, verbose_name='ظرفیت')),
                ('poster', models.ImageField(blank=True, null=True, upload_to='', verbose_name='پوستر فیلم')),
                ('is_active', models.BooleanField(default=False, verbose_name='فعال/غیرفعال')),
                ('short_desc', models.CharField(blank=True, max_length=300, null=True, verbose_name='توضیحات کوتاه')),
                ('description', models.CharField(blank=True, max_length=500, null=True, verbose_name='توضیحات')),
                ('slug', models.SlugField(blank=True, default='')),
            ],
            options={
                'verbose_name': 'فیلم',
                'verbose_name_plural': 'فیلم ها',
            },
        ),
    ]
