# Generated by Django 6.0 on 2026-01-05 09:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cinema', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='movie',
            name='max_ticket_per_user',
            field=models.PositiveIntegerField(default=4, verbose_name='حداکپر رزرو برای هر نفر'),
        ),
    ]
