# Generated by Django 6.0 on 2026-01-05 09:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cinema', '0003_moviereserve'),
    ]

    operations = [
        migrations.AlterField(
            model_name='movie',
            name='capacity',
            field=models.PositiveIntegerField(blank=True, null=True, verbose_name='ظرفیت'),
        ),
    ]
