# Generated by Django 6.0 on 2026-01-05 11:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cinema', '0004_alter_movie_capacity'),
    ]

    operations = [
        migrations.AddField(
            model_name='movie',
            name='start',
            field=models.TimeField(blank=True, null=True, verbose_name='ساعت شروع سانس'),
        ),
    ]
