# Generated by Django 6.0 on 2026-01-05 12:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cinema', '0005_movie_start'),
    ]

    operations = [
        migrations.AddField(
            model_name='moviereserve',
            name='seats',
            field=models.CharField(blank=True, max_length=200, null=True, verbose_name='شماره صندلی\u200cها'),
        ),
        migrations.AddField(
            model_name='moviereserve',
            name='show_time',
            field=models.DateTimeField(null=True, verbose_name='سانس'),
        ),
    ]
