# Generated by Django 6.0 on 2026-01-05 12:35

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cinema', '0006_moviereserve_seats_moviereserve_show_time'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='moviereserve',
            name='show_time',
        ),
        migrations.CreateModel(
            name='ShowTime',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('time', models.DateTimeField(verbose_name='زمان سانس')),
                ('movie', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='show_times', to='cinema.movie')),
            ],
            options={
                'verbose_name': 'سانس',
                'verbose_name_plural': 'سانس ها',
            },
        ),
    ]
