# Generated by Django 6.0 on 2026-01-05 12:49

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cinema', '0007_remove_moviereserve_show_time_showtime'),
    ]

    operations = [
        migrations.AddField(
            model_name='moviereserve',
            name='show_time',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='reservations', to='cinema.showtime'),
        ),
        migrations.AddField(
            model_name='showtime',
            name='capacity',
            field=models.PositiveIntegerField(blank=True, default=50, null=True),
        ),
    ]
