# Generated by Django 6.0 on 2026-01-06 09:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cinema', '0008_moviereserve_show_time_showtime_capacity'),
    ]

    operations = [
        migrations.AddField(
            model_name='movie',
            name='remaining_capacity',
            field=models.PositiveIntegerField(blank=True, null=True, verbose_name='ظرفیت باقی\u200cمانده'),
        ),
        migrations.AddField(
            model_name='movie',
            name='remaining_per_user',
            field=models.PositiveIntegerField(default=4, verbose_name='ظرفیت باقی\u200cمانده برای هر نفر'),
        ),
        migrations.AddField(
            model_name='movie',
            name='seats_left',
            field=models.PositiveIntegerField(blank=True, null=True, verbose_name='تعداد صندلی سمت چپ'),
        ),
        migrations.AddField(
            model_name='movie',
            name='seats_right',
            field=models.PositiveIntegerField(blank=True, null=True, verbose_name='تعداد صندلی سمت راست'),
        ),
    ]
