# Generated by Django 6.0 on 2026-01-30 10:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cinema', '0009_movie_remaining_capacity_movie_remaining_per_user_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='moviereserve',
            name='tracking_code',
            field=models.CharField(editable=False, max_length=36, null=True, unique=True, verbose_name='کد رهگیری'),
        ),
    ]
