# Generated by Django 6.0 on 2026-01-30 19:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cinema', '0010_moviereserve_tracking_code'),
    ]

    operations = [
        migrations.AddField(
            model_name='showtime',
            name='date',
            field=models.DateField(null=True, verbose_name='تاریخ'),
        ),
        migrations.AlterField(
            model_name='showtime',
            name='time',
            field=models.TimeField(null=True, verbose_name='زمان سانس'),
        ),
    ]
