# Generated by Django 6.0 on 2026-01-02 15:08

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(blank=True, max_length=300, null=True, verbose_name='عنوان کلاس')),
                ('age_range', models.CharField(blank=True, max_length=300, null=True, verbose_name='رنج سنی')),
                ('jalase_count', models.IntegerField(blank=True, null=True, verbose_name='تعداد جلسات')),
                ('teacher', models.CharField(blank=True, max_length=300, null=True, verbose_name='نام مدرس')),
                ('short_desc', models.CharField(blank=True, max_length=500, null=True, verbose_name='توضیحات کوتاه')),
                ('long_desc', models.TextField(blank=True, null=True, verbose_name='توضیحات بلند')),
                ('image', models.ImageField(blank=True, null=True, upload_to='media', verbose_name='تصویر')),
                ('slug', models.SlugField(blank=True, default='')),
            ],
            options={
                'verbose_name': 'کلاس',
                'verbose_name_plural': 'کلاس ها',
            },
        ),
        migrations.CreateModel(
            name='pish_sabt',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('std_name', models.CharField(max_length=300, verbose_name='نام فرزند')),
                ('std_lastname', models.CharField(max_length=300, verbose_name='نام خانوادگی فرزند')),
                ('age', models.CharField(choices=[('3-6', 'سه الی شش سال'), ('6-8', 'شش الی هشت سال'), ('8-10', 'هشت الی ده سال'), ('10-15', 'ده الی پانزده سال')], max_length=300, verbose_name='رنج سنی')),
                ('parent_name', models.CharField(max_length=300, verbose_name='نام ونام خانوادگی والد')),
                ('mobile', models.CharField(max_length=11, verbose_name='شماره تماس')),
                ('desc', models.TextField(verbose_name='توضیحات اضافی')),
                ('product_choice', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='relatedproduct', to='products.product', verbose_name='کلاس')),
            ],
            options={
                'verbose_name': 'پیش ثبت نام',
                'verbose_name_plural': 'پیش ثبت نام ها',
            },
        ),
    ]
