# Generated by Django 6.0 on 2026-01-02 15:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='pish_sabt',
            name='is_read',
            field=models.BooleanField(default=False, verbose_name='خوانده شده'),
        ),
    ]
